contact_links:
  - name: Discord
    url: https://discord.gg/congress
    about: Celeste's Discord chat room.
  - name: Matrix
    url: https://matrix.to/#/#celeste:gnome.org
    about: Celeste's Matrix chat room.
